
# [shell]
# program = "/bin/zsh"
# args = ["-c", "zellij"]


[font]
# normal = {family = "JetBrainsMono Nerd Font", style = "Medium"}
normal = {family = "GoMono Nerd Font", style = "Regular"}
size = 12
bold = {style = "Medium"}

[window]
decorations = "None"
padding.x = 16
padding.y = 14

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [
	"~/.config/alacritty/catppuccin-frappe.toml"
]
