gui:
  theme:
    activeBorderColor:
      - '#fb4934'  # Red
    inactiveBorderColor:
      - '#928374'  # Gray
    optionsTextColor:
      - '#504945'  # Dark gray
    selectedLineBgColor:
      - '#d5c4a1'  # Light beige
    selectedRangeBgColor:
      - '#d5c4a1'  # Light beige
    cherryPickedCommitBgColor:
      - '#b8bb26'  # Green
    cherryPickedCommitFgColor:
      - '#504945'  # Dark gray
    unstagedChangesColor:
      - '#fb4934'  # Red
    defaultFgColor:
      - '#3c3836'  # Dark gray
    defaultBgColor:
      - '#fbf1c7'  # Light yellow (background)

# gui:
#   theme:
#     activeBorderColor:
#       - '#ca9ee6'
#       - bold
#     inactiveBorderColor:
#       - '#a5adce'
#     optionsTextColor:
#       - '#8caaee'
#     selectedLineBgColor:
#       - '#ccd0da'
#       # - '#414559'
#     cherryPickedCommitBgColor:
#       - '#51576d'
#     cherryPickedCommitFgColor:
#       - '#ca9ee6'
#     unstagedChangesColor:
#       - '#e78284'
#     defaultFgColor:
#       # - '#c6d0f5'
#       - '#4c4f69'
#     searchingActiveBorderColor:
#       - '#e5c890'
#
#     authorColors:
#       '*': '#babbf1'
