services:
  db:
    build: .
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - toolbox-database:/var/lib/postgresql/data

volumes:
  toolbox-database:

