version: "3.8"

services:
  db:
    build: .
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - toolbox-database:/var/lib/postgresql/data

volumes:
  toolbox-database:

