
# [shell]
# program = "/bin/zsh"
# args = ["-c", "zellij"]


[font]
normal = {family = "GoMono Nerd Font", style = "Regular"}
size = 16
bold = {style = "Regular"}

[window]
decorations = "None"
padding.x = 16
padding.y = 14

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[general]
import = [
	"~/.config/alacritty/gruvbox.toml"
]
